### ISSUE TITLE
some website can not take full screenshot

### ISSUE THREAD

**Issue by nqbjnh** [Noksa/WebDriver.Screenshots.Extensions#16] opened 2019-05-06 09:11 UTC
Hi,
Website: https://www.nordstromrack.com/
This website can not take full screenshot.
I used ChromeDriver.
Do you know where the problem is?
please, help me.
Thanks you

**Comment by Noksa** [comment] 2019-05-07 12:25
Hello @nqbjnh 
I cant open this site to reproduce error. 
![image](https://user-images.githubusercontent.com/36312857/57299033-4c7eb880-70dc-11e9-8021-51191b6d0f8c.png)

**Comment by nqbjnh** [comment] 2019-05-07 13:26
This site allow ip address from USA.

Vào 19:25 T.3, 07 Th5 2019 Alexandr D. <notifications@github.com> đã viết:

**Comment by Noksa** [comment] 2019-05-08 05:58
This is a bug.

**Comment by nqbjnh** [comment] 2019-05-08 07:08
Thanks for fix,
Have you updated on nuget yet?

**Comment by Noksa** [comment] 2019-05-08 07:54
@nqbjnh 
Within an hour will be available.

**Comment by Noksa** [comment] 2019-05-08 08:14
@nqbjnh 
Package is uploaded to nuget.
Please check issue with new version and close it, if all are fine.

**Comment by nqbjnh** [comment] 2019-05-08 08:56
Hi, I updated nuget, but i get a exception.
Code:
`var imgByteArray = driver.TakeScreenshot(new VerticalCombineDecorator(new ScreenshotMaker()));`

Exception: Script returned a value, but the result could not be cast to the desired type
`   at OpenQA.Selenium.Support.Extensions.WebDriverExtensions.ExecuteJavaScript[T](IWebDriver driver, String script, Object[] args)
   at WDSE.Helpers.JQueryHelper.GetCurrentScrollLocation(IWebDriver driver, IWebElement element)
   at WDSE.Decorators.VerticalCombineDecorator.CombineScreenshots(IWebDriver driver)
   at WDSE.Decorators.VerticalCombineDecorator.MakeScreenshot(IWebDriver driver)
   at WDSE.ExtensionMethods.TakeScreenshot(IWebDriver driver, IScreenshotStrategy strategy)
   at UsExpress.Lib.AutomaticPurchases.Core.Utilities.WebDriverExtensions.TakeScreenShot(IWebDriver driver, String PathFileName) in G:\Projects\UsExpress\UsExpress_API\UsExpress.Lib.AutomaticPurchases.Core\Utilities\WebDriverExtensions.cs:line 150`

**Comment by Noksa** [comment] 2019-05-08 09:09
@nqbjnh on which site?

Same code worked on https://www.nordstromrack.com/ with 1920x1080 resolution.

```
Driver.Manage().Window.Size = new Size(1920, 1080);
Driver.Navigate().GoToUrl("https://www.nordstromrack.com/");
var screenMaker = new ScreenshotMaker();
var arr = Driver.TakeScreenshot(new VerticalCombineDecorator(screenMaker));
```

Chromedriver / chrome versions?
Resolution of screen? Maximized browser?

**Comment by nqbjnh** [comment] 2019-05-08 09:22
I copy your code, and i get error.
![error](https://user-images.githubusercontent.com/26054523/57364464-7358ef80-71ad-11e9-8105-cd477bab3bf5.png)

What is version chromedriver, .NetFramework, Chrome you use?

**Comment by Noksa** [comment] 2019-05-08 09:35
Chrome: Version 74.0.3729.131 (Official Build) (64-bit)
Chromedriver is last, used by https://github.com/rosolko/WebDriverManager.Net
.NET 4.7.1

PS: I'm upload beta with more logging and maybe fix your problem, try it please: https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.4.1-beta

**Comment by nqbjnh** [comment] 2019-05-09 02:12
I get beta version and get error
Error: **Input string was not in a correct format.**
`   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at WDSE.Helpers.JQueryHelper.GetCurrentScrollLocation(IWebDriver driver, IWebElement element)
   at WDSE.Decorators.VerticalCombineDecorator.CombineScreenshots(IWebDriver driver)
   at WDSE.Decorators.VerticalCombineDecorator.MakeScreenshot(IWebDriver driver)
   at WDSE.ExtensionMethods.TakeScreenshot(IWebDriver driver, IScreenshotStrategy strategy)
   at WinAppConfigChrome.Program.Main(String[] args) in G:\Projects\UsExpress\UsExpress_API\WinAppConfigChrome\Program.cs:line 39`

I think this function **WDSE.Helpers.JQueryHelper.GetCurrentScrollLocation** error

**Comment by Noksa** [comment] 2019-05-13 04:28
I changed the function a bit to use pure js instead of jquery and add TryParse instead of parse.
Try it please: https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.4.2-beta

**Comment by nqbjnh** [comment] 2019-05-13 07:26
I updated 0.1.4.2-beta, but i get a error:
Error: **Cant get current scroll location: 2252.80004882813**
`   at WDSE.Helpers.JQueryHelper.GetCurrentScrollLocation(IWebDriver driver, IWebElement element)
   at WDSE.Decorators.VerticalCombineDecorator.CombineScreenshots(IWebDriver driver)
   at WDSE.Decorators.VerticalCombineDecorator.MakeScreenshot(IWebDriver driver)
   at WDSE.ExtensionMethods.TakeScreenshot(IWebDriver driver, IScreenshotStrategy strategy)
   at WinAppConfigChrome.Program.Main(String[] args) in G:\Projects\UsExpress\UsExpress_API\WinAppConfigChrome\Program.cs:line 51`

![error](https://user-images.githubusercontent.com/26054523/57603093-049fdb80-758b-11e9-85d2-b2f0c6a2f868.png)

**Comment by Noksa** [comment] 2019-05-13 08:21
Okay, thanks. Now I understand what the problem is.
But i still dont understand how it's can be double, not int.

**Comment by Noksa** [comment] 2019-05-13 10:25
@nqbjnh 
This version (https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.4.3-beta) fixed this issue i guess.
But this is still not the final version and, perhaps, the entire screenshot may not be correct with the offset of a pair of pixels.
I'm need more time to investigate problem, when scrollTop returns not integer/long.

**Comment by Noksa** [comment] 2019-05-15 05:17
@nqbjnh 
Can you give feedback? It works?

**Comment by nqbjnh** [comment] 2019-05-15 05:30
Hi, 
It worked.
Thanks you so much.
![error](https://user-images.githubusercontent.com/26054523/57750628-2d4fde80-770d-11e9-9787-c5297b57fb90.png)

**Comment by Noksa** [comment] 2019-05-15 12:41
@nqbjnh 
Glad to hear that. :)

**Closed as completed by Noksa** 2019-05-15 12:41 UTC
Labels: bug, released

**Comment by anvilnext** [comment] 2020-02-18 14:08
Hey. I don't understand how to save the screenshot on a disk.
